# -*- coding: utf-8 -*-
"""Portofolio Batch 19 - Hawa Andini Hadi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fqu3duSM8-ECjRDaW_qbU5ldEmYsZbIX

**Data Exploration & Preparation**
"""

#Import dataset
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
df = pd.read_excel('/content/drive/MyDrive/Batch_19/student_performance.xlsx')

df.head()

#Column types and non-null counts
df.info()

#Missing values
df.isna().sum()

#Duplicated
df.duplicated().sum()

"""**Data Preprocessing**"""

import pandas as pd

print(df['Attendance_Rate'].describe())
print(df['Attendance_(%)'].describe())

#Drop the Attendance (%) column
df = df.drop(columns=['Attendance_(%)'])

#Check if the column has been removed
print(df.columns)

#Reformat StudentID
df['Student_ID'] = ['S' + str(i).zfill(3) for i in range(1, len(df) + 1)]

#Remove rows where both Name and Gender are missing (if still any)
df = df[~(df['Name'].isnull() & df['Gender'].isnull())]

#Replace missing names based on gender
df.loc[df['Name'].isnull() & (df['Gender'] == 0), 'Name'] = 'Unknown_Male'
df.loc[df['Name'].isnull() & (df['Gender'] == 1), 'Name'] = 'Unknown_Female'

df['Name'].isnull().sum()

df.head()

#Handling Missing Values Using Mode and Median Imputation
#Fill categorical columns with their mode (most frequent value)
df['Parental_Support'] = df['Parental_Support'].fillna(df['Parental_Support'].mode()[0])
df['Online_Classes_Taken'] = df['Online_Classes_Taken'].fillna(df['Online_Classes_Taken'].mode()[0])

#List of numerical columns to fill with median values
cols_median = [
    'Attendance_Rate', 'Study_Hours_Per_Week', 'Previous_Grade',
    'Extracurricular_Activities', 'Final_Grade'
]

#Fill missing values in numerical columns using median
for col in cols_median:
    df[col] = df[col].fillna(df[col].median())

#Missing values
df.isna().sum()

"""**Data Transformation**"""

#Create Average_Score
df['Average_Score'] = df[['Previous_Grade', 'Final_Grade']].mean(axis=1)

#Create Performance_Level
def performance_level(x):
    if x >= 80:
        return 'High'
    elif x >= 75:
        return 'Medium'
    else:
        return 'Low'

df['Performance_Level'] = df['Average_Score'].apply(performance_level)
df[['Name', 'Average_Score', 'Performance_Level']].head(10)

import pandas as pd

# Convert Gender from numeric to string
gender_reverse = {0: 'Male', 1: 'Female'}
df['Gender'] = df['Gender'].map(gender_reverse).astype('object')

# Convert Parental_Support from numeric to string
parental_reverse = {0: 'Low', 1: 'Medium', 2: 'High'}
df['Parental_Support'] = df['Parental_Support'].map(parental_reverse).astype('object')

# Convert Online_Classes_Taken from numeric to string
online_reverse = {0: 'False', 1: 'True'}
df['Online_Classes_Taken'] = df['Online_Classes_Taken'].map(online_reverse).astype('object')

print(df[['Gender','Parental_Support','Online_Classes_Taken']].head())

#Column types and non-null counts
df.info()

#Save dataset to an Excel file (.xlsx)
df.to_excel('/content/drive/MyDrive/Batch_19/student_performance_final.xlsx', index=False)

print("Saved to Excel!")

"""**Machine Learning**"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd

# Separate features and target
X = df[['Study_Hours_Per_Week', 'Attendance_Rate']]
y = df['Final_Grade']

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train a simple model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Display first 5 predictions vs actual values
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(comparison.head())

import matplotlib.pyplot as plt
import seaborn as sns

#Compare actual vs predicted
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

#Plot 1: Scatter plot of Actual vs Predicted
plt.figure(figsize=(8,6))
sns.scatterplot(x='Actual', y='Predicted', data=comparison)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')  # 45-degree line
plt.xlabel('Actual Final Grade')
plt.ylabel('Predicted Final Grade')
plt.title('Actual vs Predicted Final Grades')
plt.show()

#Plot 2 (optional): Line plot of first 20 predictions
comparison.head(20).plot(kind='bar', figsize=(10,6))
plt.title('First 20 Actual vs Predicted Final Grades')
plt.xlabel('Index')
plt.ylabel('Final Grade')
plt.xticks(rotation=0)
plt.show()